/* --------------------------------------------------------------------------------
  This file was automatically generated by the Athlos Project Editor.
  Athlos Framework: http://nkasenides.github.io/athlos
  Generated on: 16-11-2021 12:37:22
  Athlos Project Editor, v0.1.0 BETA
-------------------------------------------------------------------------------- */


package com.nkasenides.minesweeper.model;

import com.nkasenides.minesweeper.proto.*;
import com.nkasenides.athlos.model.*;
import com.nkasenides.athlos.proto.*;



public interface MAEntity extends IEntity, GenericTransmittable<MAEntityProto.Builder> {

    String getWorldID();    
    float getAreaOfInterest();    
    String getId();    
    MatrixPosition getPosition();    
    String getPlayerID();    
    Direction4 getDirection();    
    void setWorldID(String worldID);    
    void setAreaOfInterest(float areaOfInterest);    
    void setId(String id);    
    void setPosition(MatrixPosition position);    
    void setPlayerID(String playerID);    
    void setDirection(Direction4 direction);    

}

