/* --------------------------------------------------------------------------------
  This file was automatically generated by the Athlos Project Editor.
  Athlos Framework: http://nkasenides.github.io/athlos
  Generated on: 16-11-2021 12:37:22
  Athlos Project Editor, v0.1.0 BETA
-------------------------------------------------------------------------------- */

package com.nkasenides.minesweeper.model;

import com.nkasenides.athlos.proto.Transmittable;
import com.nkasenides.athlos.proto.GenericTransmittable;
import com.nkasenides.minesweeper.proto.*;
import com.nkasenides.athlos.model.*;
import com.raylabz.objectis.annotation.ObjectisObject;

import java.io.Serializable;

@ObjectisObject
public class MAPlayer implements IPlayer, Transmittable<MAPlayerProto.Builder>, Serializable {
    private String password;    
    private String teamID;    
    private String name;    
    private String id;    
    private long createdOn;

    public MAPlayer() { } //NEW

    public String getPassword() {    
        return password;        
    }    
    
    public String getTeamID() {    
        return teamID;        
    }    
    
    public String getName() {    
        return name;        
    }    
    
    public String getId() {    
        return id;        
    }    
    
    public long getCreatedOn() {    
        return createdOn;        
    }    
    

    public void setPassword(String password) {    
        this.password = password;        
    }    
    
    public void setTeamID(String teamID) {    
        this.teamID = teamID;        
    }    
    
    public void setName(String name) {    
        this.name = name;        
    }    
    
    public void setId(String id) {    
        this.id = id;        
    }    
    
    public void setCreatedOn(long createdOn) {    
        this.createdOn = createdOn;        
    }    
    

    @Override    
    public com.nkasenides.minesweeper.proto.MAPlayerProto.Builder toProto() {    
        com.nkasenides.minesweeper.proto.MAPlayerProto.Builder protoBuilder = com.nkasenides.minesweeper.proto.MAPlayerProto.newBuilder();        
        protoBuilder.setPassword(password);        
        protoBuilder.setTeamID(teamID);        
        protoBuilder.setName(name);        
        protoBuilder.setId(id);        
        protoBuilder.setCreatedOn(createdOn);        
        return protoBuilder;        
    }    
    

}
