// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto/MProto.proto

package com.nkasenides.minesweeper.proto;

/**
 * Protobuf type {@code com.nkasenides.minesweeper.proto.CreateGameRequest}
 */
public final class CreateGameRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.nkasenides.minesweeper.proto.CreateGameRequest)
    CreateGameRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateGameRequest.newBuilder() to construct.
  private CreateGameRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateGameRequest() {
    difficulty_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateGameRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateGameRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            difficulty_ = rawValue;
            break;
          }
          case 16: {

            width_ = input.readUInt32();
            break;
          }
          case 24: {

            maxPlayers_ = input.readUInt32();
            break;
          }
          case 32: {

            height_ = input.readUInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nkasenides.minesweeper.proto.MProto.internal_static_com_nkasenides_minesweeper_proto_CreateGameRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nkasenides.minesweeper.proto.MProto.internal_static_com_nkasenides_minesweeper_proto_CreateGameRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nkasenides.minesweeper.proto.CreateGameRequest.class, com.nkasenides.minesweeper.proto.CreateGameRequest.Builder.class);
  }

  public static final int DIFFICULTY_FIELD_NUMBER = 1;
  private int difficulty_;
  /**
   * <code>.com.nkasenides.minesweeper.proto.Difficulty difficulty = 1;</code>
   * @return The enum numeric value on the wire for difficulty.
   */
  @java.lang.Override public int getDifficultyValue() {
    return difficulty_;
  }
  /**
   * <code>.com.nkasenides.minesweeper.proto.Difficulty difficulty = 1;</code>
   * @return The difficulty.
   */
  @java.lang.Override public com.nkasenides.minesweeper.proto.Difficulty getDifficulty() {
    @SuppressWarnings("deprecation")
    com.nkasenides.minesweeper.proto.Difficulty result = com.nkasenides.minesweeper.proto.Difficulty.valueOf(difficulty_);
    return result == null ? com.nkasenides.minesweeper.proto.Difficulty.UNRECOGNIZED : result;
  }

  public static final int WIDTH_FIELD_NUMBER = 2;
  private int width_;
  /**
   * <code>uint32 width = 2;</code>
   * @return The width.
   */
  @java.lang.Override
  public int getWidth() {
    return width_;
  }

  public static final int MAXPLAYERS_FIELD_NUMBER = 3;
  private int maxPlayers_;
  /**
   * <code>uint32 maxPlayers = 3;</code>
   * @return The maxPlayers.
   */
  @java.lang.Override
  public int getMaxPlayers() {
    return maxPlayers_;
  }

  public static final int HEIGHT_FIELD_NUMBER = 4;
  private int height_;
  /**
   * <code>uint32 height = 4;</code>
   * @return The height.
   */
  @java.lang.Override
  public int getHeight() {
    return height_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (difficulty_ != com.nkasenides.minesweeper.proto.Difficulty.EASY_Difficulty.getNumber()) {
      output.writeEnum(1, difficulty_);
    }
    if (width_ != 0) {
      output.writeUInt32(2, width_);
    }
    if (maxPlayers_ != 0) {
      output.writeUInt32(3, maxPlayers_);
    }
    if (height_ != 0) {
      output.writeUInt32(4, height_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (difficulty_ != com.nkasenides.minesweeper.proto.Difficulty.EASY_Difficulty.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, difficulty_);
    }
    if (width_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, width_);
    }
    if (maxPlayers_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, maxPlayers_);
    }
    if (height_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, height_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nkasenides.minesweeper.proto.CreateGameRequest)) {
      return super.equals(obj);
    }
    com.nkasenides.minesweeper.proto.CreateGameRequest other = (com.nkasenides.minesweeper.proto.CreateGameRequest) obj;

    if (difficulty_ != other.difficulty_) return false;
    if (getWidth()
        != other.getWidth()) return false;
    if (getMaxPlayers()
        != other.getMaxPlayers()) return false;
    if (getHeight()
        != other.getHeight()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DIFFICULTY_FIELD_NUMBER;
    hash = (53 * hash) + difficulty_;
    hash = (37 * hash) + WIDTH_FIELD_NUMBER;
    hash = (53 * hash) + getWidth();
    hash = (37 * hash) + MAXPLAYERS_FIELD_NUMBER;
    hash = (53 * hash) + getMaxPlayers();
    hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + getHeight();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nkasenides.minesweeper.proto.CreateGameRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nkasenides.minesweeper.proto.CreateGameRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nkasenides.minesweeper.proto.CreateGameRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nkasenides.minesweeper.proto.CreateGameRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nkasenides.minesweeper.proto.CreateGameRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nkasenides.minesweeper.proto.CreateGameRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nkasenides.minesweeper.proto.CreateGameRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nkasenides.minesweeper.proto.CreateGameRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nkasenides.minesweeper.proto.CreateGameRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.nkasenides.minesweeper.proto.CreateGameRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nkasenides.minesweeper.proto.CreateGameRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nkasenides.minesweeper.proto.CreateGameRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nkasenides.minesweeper.proto.CreateGameRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.nkasenides.minesweeper.proto.CreateGameRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.nkasenides.minesweeper.proto.CreateGameRequest)
      com.nkasenides.minesweeper.proto.CreateGameRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nkasenides.minesweeper.proto.MProto.internal_static_com_nkasenides_minesweeper_proto_CreateGameRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nkasenides.minesweeper.proto.MProto.internal_static_com_nkasenides_minesweeper_proto_CreateGameRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nkasenides.minesweeper.proto.CreateGameRequest.class, com.nkasenides.minesweeper.proto.CreateGameRequest.Builder.class);
    }

    // Construct using com.nkasenides.minesweeper.proto.CreateGameRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      difficulty_ = 0;

      width_ = 0;

      maxPlayers_ = 0;

      height_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nkasenides.minesweeper.proto.MProto.internal_static_com_nkasenides_minesweeper_proto_CreateGameRequest_descriptor;
    }

    @java.lang.Override
    public com.nkasenides.minesweeper.proto.CreateGameRequest getDefaultInstanceForType() {
      return com.nkasenides.minesweeper.proto.CreateGameRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.nkasenides.minesweeper.proto.CreateGameRequest build() {
      com.nkasenides.minesweeper.proto.CreateGameRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.nkasenides.minesweeper.proto.CreateGameRequest buildPartial() {
      com.nkasenides.minesweeper.proto.CreateGameRequest result = new com.nkasenides.minesweeper.proto.CreateGameRequest(this);
      result.difficulty_ = difficulty_;
      result.width_ = width_;
      result.maxPlayers_ = maxPlayers_;
      result.height_ = height_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nkasenides.minesweeper.proto.CreateGameRequest) {
        return mergeFrom((com.nkasenides.minesweeper.proto.CreateGameRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nkasenides.minesweeper.proto.CreateGameRequest other) {
      if (other == com.nkasenides.minesweeper.proto.CreateGameRequest.getDefaultInstance()) return this;
      if (other.difficulty_ != 0) {
        setDifficultyValue(other.getDifficultyValue());
      }
      if (other.getWidth() != 0) {
        setWidth(other.getWidth());
      }
      if (other.getMaxPlayers() != 0) {
        setMaxPlayers(other.getMaxPlayers());
      }
      if (other.getHeight() != 0) {
        setHeight(other.getHeight());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.nkasenides.minesweeper.proto.CreateGameRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.nkasenides.minesweeper.proto.CreateGameRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int difficulty_ = 0;
    /**
     * <code>.com.nkasenides.minesweeper.proto.Difficulty difficulty = 1;</code>
     * @return The enum numeric value on the wire for difficulty.
     */
    @java.lang.Override public int getDifficultyValue() {
      return difficulty_;
    }
    /**
     * <code>.com.nkasenides.minesweeper.proto.Difficulty difficulty = 1;</code>
     * @param value The enum numeric value on the wire for difficulty to set.
     * @return This builder for chaining.
     */
    public Builder setDifficultyValue(int value) {
      
      difficulty_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.nkasenides.minesweeper.proto.Difficulty difficulty = 1;</code>
     * @return The difficulty.
     */
    @java.lang.Override
    public com.nkasenides.minesweeper.proto.Difficulty getDifficulty() {
      @SuppressWarnings("deprecation")
      com.nkasenides.minesweeper.proto.Difficulty result = com.nkasenides.minesweeper.proto.Difficulty.valueOf(difficulty_);
      return result == null ? com.nkasenides.minesweeper.proto.Difficulty.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.nkasenides.minesweeper.proto.Difficulty difficulty = 1;</code>
     * @param value The difficulty to set.
     * @return This builder for chaining.
     */
    public Builder setDifficulty(com.nkasenides.minesweeper.proto.Difficulty value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      difficulty_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.nkasenides.minesweeper.proto.Difficulty difficulty = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDifficulty() {
      
      difficulty_ = 0;
      onChanged();
      return this;
    }

    private int width_ ;
    /**
     * <code>uint32 width = 2;</code>
     * @return The width.
     */
    @java.lang.Override
    public int getWidth() {
      return width_;
    }
    /**
     * <code>uint32 width = 2;</code>
     * @param value The width to set.
     * @return This builder for chaining.
     */
    public Builder setWidth(int value) {
      
      width_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 width = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearWidth() {
      
      width_ = 0;
      onChanged();
      return this;
    }

    private int maxPlayers_ ;
    /**
     * <code>uint32 maxPlayers = 3;</code>
     * @return The maxPlayers.
     */
    @java.lang.Override
    public int getMaxPlayers() {
      return maxPlayers_;
    }
    /**
     * <code>uint32 maxPlayers = 3;</code>
     * @param value The maxPlayers to set.
     * @return This builder for chaining.
     */
    public Builder setMaxPlayers(int value) {
      
      maxPlayers_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 maxPlayers = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxPlayers() {
      
      maxPlayers_ = 0;
      onChanged();
      return this;
    }

    private int height_ ;
    /**
     * <code>uint32 height = 4;</code>
     * @return The height.
     */
    @java.lang.Override
    public int getHeight() {
      return height_;
    }
    /**
     * <code>uint32 height = 4;</code>
     * @param value The height to set.
     * @return This builder for chaining.
     */
    public Builder setHeight(int value) {
      
      height_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 height = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearHeight() {
      
      height_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.nkasenides.minesweeper.proto.CreateGameRequest)
  }

  // @@protoc_insertion_point(class_scope:com.nkasenides.minesweeper.proto.CreateGameRequest)
  private static final com.nkasenides.minesweeper.proto.CreateGameRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nkasenides.minesweeper.proto.CreateGameRequest();
  }

  public static com.nkasenides.minesweeper.proto.CreateGameRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateGameRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateGameRequest>() {
    @java.lang.Override
    public CreateGameRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateGameRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateGameRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateGameRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.nkasenides.minesweeper.proto.CreateGameRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

