// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto/MProto.proto

package com.nkasenides.minesweeper.proto;

public interface JoinGameRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.nkasenides.minesweeper.proto.JoinGameRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string gameID = 1;</code>
   * @return The gameID.
   */
  String getGameID();
  /**
   * <code>string gameID = 1;</code>
   * @return The bytes for gameID.
   */
  com.google.protobuf.ByteString
      getGameIDBytes();

  /**
   * <code>string gameSessionID = 2;</code>
   * @return The gameSessionID.
   */
  String getGameSessionID();
  /**
   * <code>string gameSessionID = 2;</code>
   * @return The bytes for gameSessionID.
   */
  com.google.protobuf.ByteString
      getGameSessionIDBytes();

  /**
   * <code>.com.nkasenides.minesweeper.proto.PartialStatePreferenceProto partialStatePreference = 3;</code>
   * @return Whether the partialStatePreference field is set.
   */
  boolean hasPartialStatePreference();
  /**
   * <code>.com.nkasenides.minesweeper.proto.PartialStatePreferenceProto partialStatePreference = 3;</code>
   * @return The partialStatePreference.
   */
  PartialStatePreferenceProto getPartialStatePreference();
  /**
   * <code>.com.nkasenides.minesweeper.proto.PartialStatePreferenceProto partialStatePreference = 3;</code>
   */
  PartialStatePreferenceProtoOrBuilder getPartialStatePreferenceOrBuilder();
}
