// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto/MProto.proto

package com.nkasenides.minesweeper.proto;

/**
 * Protobuf type {@code com.nkasenides.minesweeper.proto.MAEntityProto}
 */
public final class MAEntityProto extends
    com.google.protobuf.GeneratedMessageV3 implements com.nkasenides.athlos.model.IEntity, 
    // @@protoc_insertion_point(message_implements:com.nkasenides.minesweeper.proto.MAEntityProto)
    MAEntityProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MAEntityProto.newBuilder() to construct.
  private MAEntityProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MAEntityProto() {
    worldID_ = "";
    id_ = "";
    playerID_ = "";
    direction_ = 0;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new MAEntityProto();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MAEntityProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            worldID_ = s;
            break;
          }
          case 21: {

            areaOfInterest_ = input.readFloat();
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 34: {
            MatrixPositionProto.Builder subBuilder = null;
            if (position_ != null) {
              subBuilder = position_.toBuilder();
            }
            position_ = input.readMessage(MatrixPositionProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(position_);
              position_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            playerID_ = s;
            break;
          }
          case 48: {
            int rawValue = input.readEnum();

            direction_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return MProto.internal_static_com_nkasenides_minesweeper_proto_MAEntityProto_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return MProto.internal_static_com_nkasenides_minesweeper_proto_MAEntityProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            MAEntityProto.class, Builder.class);
  }

  public static final int WORLDID_FIELD_NUMBER = 1;
  private volatile Object worldID_;
  /**
   * <code>string worldID = 1;</code>
   * @return The worldID.
   */
  @Override
  public String getWorldID() {
    Object ref = worldID_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      worldID_ = s;
      return s;
    }
  }
  /**
   * <code>string worldID = 1;</code>
   * @return The bytes for worldID.
   */
  @Override
  public com.google.protobuf.ByteString
      getWorldIDBytes() {
    Object ref = worldID_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      worldID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AREAOFINTEREST_FIELD_NUMBER = 2;
  private float areaOfInterest_;
  /**
   * <code>float areaOfInterest = 2;</code>
   * @return The areaOfInterest.
   */
  @Override
  public float getAreaOfInterest() {
    return areaOfInterest_;
  }

  public static final int ID_FIELD_NUMBER = 3;
  private volatile Object id_;
  /**
   * <code>string id = 3;</code>
   * @return The id.
   */
  @Override
  public String getId() {
    Object ref = id_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 3;</code>
   * @return The bytes for id.
   */
  @Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    Object ref = id_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POSITION_FIELD_NUMBER = 4;
  private MatrixPositionProto position_;
  /**
   * <code>.com.nkasenides.minesweeper.proto.MatrixPositionProto position = 4;</code>
   * @return Whether the position field is set.
   */
  @Override
  public boolean hasPosition() {
    return position_ != null;
  }
  /**
   * <code>.com.nkasenides.minesweeper.proto.MatrixPositionProto position = 4;</code>
   * @return The position.
   */
  @Override
  public MatrixPositionProto getPosition() {
    return position_ == null ? MatrixPositionProto.getDefaultInstance() : position_;
  }
  /**
   * <code>.com.nkasenides.minesweeper.proto.MatrixPositionProto position = 4;</code>
   */
  @Override
  public MatrixPositionProtoOrBuilder getPositionOrBuilder() {
    return getPosition();
  }

  public static final int PLAYERID_FIELD_NUMBER = 5;
  private volatile Object playerID_;
  /**
   * <code>string playerID = 5;</code>
   * @return The playerID.
   */
  @Override
  public String getPlayerID() {
    Object ref = playerID_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      playerID_ = s;
      return s;
    }
  }
  /**
   * <code>string playerID = 5;</code>
   * @return The bytes for playerID.
   */
  @Override
  public com.google.protobuf.ByteString
      getPlayerIDBytes() {
    Object ref = playerID_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      playerID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DIRECTION_FIELD_NUMBER = 6;
  private int direction_;
  /**
   * <code>.com.nkasenides.minesweeper.proto.Direction4 direction = 6;</code>
   * @return The enum numeric value on the wire for direction.
   */
  @Override public int getDirectionValue() {
    return direction_;
  }
  /**
   * <code>.com.nkasenides.minesweeper.proto.Direction4 direction = 6;</code>
   * @return The direction.
   */
  @Override public Direction4 getDirection() {
    @SuppressWarnings("deprecation")
    Direction4 result = Direction4.valueOf(direction_);
    return result == null ? Direction4.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getWorldIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, worldID_);
    }
    if (areaOfInterest_ != 0F) {
      output.writeFloat(2, areaOfInterest_);
    }
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, id_);
    }
    if (position_ != null) {
      output.writeMessage(4, getPosition());
    }
    if (!getPlayerIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, playerID_);
    }
    if (direction_ != Direction4.NORTH.getNumber()) {
      output.writeEnum(6, direction_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getWorldIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, worldID_);
    }
    if (areaOfInterest_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, areaOfInterest_);
    }
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, id_);
    }
    if (position_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getPosition());
    }
    if (!getPlayerIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, playerID_);
    }
    if (direction_ != Direction4.NORTH.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, direction_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof MAEntityProto)) {
      return super.equals(obj);
    }
    MAEntityProto other = (MAEntityProto) obj;

    if (!getWorldID()
        .equals(other.getWorldID())) return false;
    if (Float.floatToIntBits(getAreaOfInterest())
        != Float.floatToIntBits(
            other.getAreaOfInterest())) return false;
    if (!getId()
        .equals(other.getId())) return false;
    if (hasPosition() != other.hasPosition()) return false;
    if (hasPosition()) {
      if (!getPosition()
          .equals(other.getPosition())) return false;
    }
    if (!getPlayerID()
        .equals(other.getPlayerID())) return false;
    if (direction_ != other.direction_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + WORLDID_FIELD_NUMBER;
    hash = (53 * hash) + getWorldID().hashCode();
    hash = (37 * hash) + AREAOFINTEREST_FIELD_NUMBER;
    hash = (53 * hash) + Float.floatToIntBits(
        getAreaOfInterest());
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    if (hasPosition()) {
      hash = (37 * hash) + POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getPosition().hashCode();
    }
    hash = (37 * hash) + PLAYERID_FIELD_NUMBER;
    hash = (53 * hash) + getPlayerID().hashCode();
    hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
    hash = (53 * hash) + direction_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static MAEntityProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MAEntityProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MAEntityProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MAEntityProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MAEntityProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MAEntityProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MAEntityProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MAEntityProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static MAEntityProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static MAEntityProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static MAEntityProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MAEntityProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(MAEntityProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.nkasenides.minesweeper.proto.MAEntityProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements com.nkasenides.athlos.model.IEntity, :com.nkasenides.minesweeper.proto.MAEntityProto)
      MAEntityProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MProto.internal_static_com_nkasenides_minesweeper_proto_MAEntityProto_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MProto.internal_static_com_nkasenides_minesweeper_proto_MAEntityProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MAEntityProto.class, Builder.class);
    }

    // Construct using com.nkasenides.minesweeper.proto.MAEntityProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      worldID_ = "";

      areaOfInterest_ = 0F;

      id_ = "";

      if (positionBuilder_ == null) {
        position_ = null;
      } else {
        position_ = null;
        positionBuilder_ = null;
      }
      playerID_ = "";

      direction_ = 0;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return MProto.internal_static_com_nkasenides_minesweeper_proto_MAEntityProto_descriptor;
    }

    @Override
    public MAEntityProto getDefaultInstanceForType() {
      return MAEntityProto.getDefaultInstance();
    }

    @Override
    public MAEntityProto build() {
      MAEntityProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public MAEntityProto buildPartial() {
      MAEntityProto result = new MAEntityProto(this);
      result.worldID_ = worldID_;
      result.areaOfInterest_ = areaOfInterest_;
      result.id_ = id_;
      if (positionBuilder_ == null) {
        result.position_ = position_;
      } else {
        result.position_ = positionBuilder_.build();
      }
      result.playerID_ = playerID_;
      result.direction_ = direction_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof MAEntityProto) {
        return mergeFrom((MAEntityProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(MAEntityProto other) {
      if (other == MAEntityProto.getDefaultInstance()) return this;
      if (!other.getWorldID().isEmpty()) {
        worldID_ = other.worldID_;
        onChanged();
      }
      if (other.getAreaOfInterest() != 0F) {
        setAreaOfInterest(other.getAreaOfInterest());
      }
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (other.hasPosition()) {
        mergePosition(other.getPosition());
      }
      if (!other.getPlayerID().isEmpty()) {
        playerID_ = other.playerID_;
        onChanged();
      }
      if (other.direction_ != 0) {
        setDirectionValue(other.getDirectionValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      MAEntityProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (MAEntityProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object worldID_ = "";
    /**
     * <code>string worldID = 1;</code>
     * @return The worldID.
     */
    public String getWorldID() {
      Object ref = worldID_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        worldID_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string worldID = 1;</code>
     * @return The bytes for worldID.
     */
    public com.google.protobuf.ByteString
        getWorldIDBytes() {
      Object ref = worldID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        worldID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string worldID = 1;</code>
     * @param value The worldID to set.
     * @return This builder for chaining.
     */
    public Builder setWorldID(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      worldID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string worldID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearWorldID() {
      
      worldID_ = getDefaultInstance().getWorldID();
      onChanged();
      return this;
    }
    /**
     * <code>string worldID = 1;</code>
     * @param value The bytes for worldID to set.
     * @return This builder for chaining.
     */
    public Builder setWorldIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      worldID_ = value;
      onChanged();
      return this;
    }

    private float areaOfInterest_ ;
    /**
     * <code>float areaOfInterest = 2;</code>
     * @return The areaOfInterest.
     */
    @Override
    public float getAreaOfInterest() {
      return areaOfInterest_;
    }
    /**
     * <code>float areaOfInterest = 2;</code>
     * @param value The areaOfInterest to set.
     * @return This builder for chaining.
     */
    public Builder setAreaOfInterest(float value) {
      
      areaOfInterest_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float areaOfInterest = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAreaOfInterest() {
      
      areaOfInterest_ = 0F;
      onChanged();
      return this;
    }

    private Object id_ = "";
    /**
     * <code>string id = 3;</code>
     * @return The id.
     */
    public String getId() {
      Object ref = id_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string id = 3;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 3;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 3;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private MatrixPositionProto position_;
    private com.google.protobuf.SingleFieldBuilderV3<
        MatrixPositionProto, MatrixPositionProto.Builder, MatrixPositionProtoOrBuilder> positionBuilder_;
    /**
     * <code>.com.nkasenides.minesweeper.proto.MatrixPositionProto position = 4;</code>
     * @return Whether the position field is set.
     */
    public boolean hasPosition() {
      return positionBuilder_ != null || position_ != null;
    }
    /**
     * <code>.com.nkasenides.minesweeper.proto.MatrixPositionProto position = 4;</code>
     * @return The position.
     */
    public MatrixPositionProto getPosition() {
      if (positionBuilder_ == null) {
        return position_ == null ? MatrixPositionProto.getDefaultInstance() : position_;
      } else {
        return positionBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.nkasenides.minesweeper.proto.MatrixPositionProto position = 4;</code>
     */
    public Builder setPosition(MatrixPositionProto value) {
      if (positionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        position_ = value;
        onChanged();
      } else {
        positionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.nkasenides.minesweeper.proto.MatrixPositionProto position = 4;</code>
     */
    public Builder setPosition(
        MatrixPositionProto.Builder builderForValue) {
      if (positionBuilder_ == null) {
        position_ = builderForValue.build();
        onChanged();
      } else {
        positionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.nkasenides.minesweeper.proto.MatrixPositionProto position = 4;</code>
     */
    public Builder mergePosition(MatrixPositionProto value) {
      if (positionBuilder_ == null) {
        if (position_ != null) {
          position_ =
            MatrixPositionProto.newBuilder(position_).mergeFrom(value).buildPartial();
        } else {
          position_ = value;
        }
        onChanged();
      } else {
        positionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.nkasenides.minesweeper.proto.MatrixPositionProto position = 4;</code>
     */
    public Builder clearPosition() {
      if (positionBuilder_ == null) {
        position_ = null;
        onChanged();
      } else {
        position_ = null;
        positionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.nkasenides.minesweeper.proto.MatrixPositionProto position = 4;</code>
     */
    public MatrixPositionProto.Builder getPositionBuilder() {
      
      onChanged();
      return getPositionFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.nkasenides.minesweeper.proto.MatrixPositionProto position = 4;</code>
     */
    public MatrixPositionProtoOrBuilder getPositionOrBuilder() {
      if (positionBuilder_ != null) {
        return positionBuilder_.getMessageOrBuilder();
      } else {
        return position_ == null ?
            MatrixPositionProto.getDefaultInstance() : position_;
      }
    }
    /**
     * <code>.com.nkasenides.minesweeper.proto.MatrixPositionProto position = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        MatrixPositionProto, MatrixPositionProto.Builder, MatrixPositionProtoOrBuilder>
        getPositionFieldBuilder() {
      if (positionBuilder_ == null) {
        positionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            MatrixPositionProto, MatrixPositionProto.Builder, MatrixPositionProtoOrBuilder>(
                getPosition(),
                getParentForChildren(),
                isClean());
        position_ = null;
      }
      return positionBuilder_;
    }

    private Object playerID_ = "";
    /**
     * <code>string playerID = 5;</code>
     * @return The playerID.
     */
    public String getPlayerID() {
      Object ref = playerID_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        playerID_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string playerID = 5;</code>
     * @return The bytes for playerID.
     */
    public com.google.protobuf.ByteString
        getPlayerIDBytes() {
      Object ref = playerID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        playerID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string playerID = 5;</code>
     * @param value The playerID to set.
     * @return This builder for chaining.
     */
    public Builder setPlayerID(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      playerID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string playerID = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlayerID() {
      
      playerID_ = getDefaultInstance().getPlayerID();
      onChanged();
      return this;
    }
    /**
     * <code>string playerID = 5;</code>
     * @param value The bytes for playerID to set.
     * @return This builder for chaining.
     */
    public Builder setPlayerIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      playerID_ = value;
      onChanged();
      return this;
    }

    private int direction_ = 0;
    /**
     * <code>.com.nkasenides.minesweeper.proto.Direction4 direction = 6;</code>
     * @return The enum numeric value on the wire for direction.
     */
    @Override public int getDirectionValue() {
      return direction_;
    }
    /**
     * <code>.com.nkasenides.minesweeper.proto.Direction4 direction = 6;</code>
     * @param value The enum numeric value on the wire for direction to set.
     * @return This builder for chaining.
     */
    public Builder setDirectionValue(int value) {
      
      direction_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.nkasenides.minesweeper.proto.Direction4 direction = 6;</code>
     * @return The direction.
     */
    @Override
    public Direction4 getDirection() {
      @SuppressWarnings("deprecation")
      Direction4 result = Direction4.valueOf(direction_);
      return result == null ? Direction4.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.nkasenides.minesweeper.proto.Direction4 direction = 6;</code>
     * @param value The direction to set.
     * @return This builder for chaining.
     */
    public Builder setDirection(Direction4 value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      direction_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.nkasenides.minesweeper.proto.Direction4 direction = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearDirection() {
      
      direction_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.nkasenides.minesweeper.proto.MAEntityProto)
  }

  // @@protoc_insertion_point(class_scope:com.nkasenides.minesweeper.proto.MAEntityProto)
  private static final MAEntityProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new MAEntityProto();
  }

  public static MAEntityProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MAEntityProto>
      PARSER = new com.google.protobuf.AbstractParser<MAEntityProto>() {
    @Override
    public MAEntityProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MAEntityProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MAEntityProto> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<MAEntityProto> getParserForType() {
    return PARSER;
  }

  @Override
  public MAEntityProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

