// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto/MProto.proto

package com.nkasenides.minesweeper.proto;

public interface MAPartialStateProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.nkasenides.minesweeper.proto.MAPartialStateProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.nkasenides.minesweeper.proto.MAWorldSessionProto worldSession = 1;</code>
   * @return Whether the worldSession field is set.
   */
  boolean hasWorldSession();
  /**
   * <code>.com.nkasenides.minesweeper.proto.MAWorldSessionProto worldSession = 1;</code>
   * @return The worldSession.
   */
  MAWorldSessionProto getWorldSession();
  /**
   * <code>.com.nkasenides.minesweeper.proto.MAWorldSessionProto worldSession = 1;</code>
   */
  MAWorldSessionProtoOrBuilder getWorldSessionOrBuilder();

  /**
   * <code>.com.nkasenides.minesweeper.proto.GameState gameState = 2;</code>
   * @return The enum numeric value on the wire for gameState.
   */
  int getGameStateValue();
  /**
   * <code>.com.nkasenides.minesweeper.proto.GameState gameState = 2;</code>
   * @return The gameState.
   */
  GameState getGameState();

  /**
   * <code>map&lt;string, .com.nkasenides.minesweeper.proto.MAEntityProto&gt; entities = 3;</code>
   */
  int getEntitiesCount();
  /**
   * <code>map&lt;string, .com.nkasenides.minesweeper.proto.MAEntityProto&gt; entities = 3;</code>
   */
  boolean containsEntities(
      String key);
  /**
   * Use {@link #getEntitiesMap()} instead.
   */
  @Deprecated
  java.util.Map<String, MAEntityProto>
  getEntities();
  /**
   * <code>map&lt;string, .com.nkasenides.minesweeper.proto.MAEntityProto&gt; entities = 3;</code>
   */
  java.util.Map<String, MAEntityProto>
  getEntitiesMap();
  /**
   * <code>map&lt;string, .com.nkasenides.minesweeper.proto.MAEntityProto&gt; entities = 3;</code>
   */

  MAEntityProto getEntitiesOrDefault(
      String key,
      MAEntityProto defaultValue);
  /**
   * <code>map&lt;string, .com.nkasenides.minesweeper.proto.MAEntityProto&gt; entities = 3;</code>
   */

  MAEntityProto getEntitiesOrThrow(
      String key);

  /**
   * <code>map&lt;string, .com.nkasenides.minesweeper.proto.MATerrainCellProto&gt; terrain = 4;</code>
   */
  int getTerrainCount();
  /**
   * <code>map&lt;string, .com.nkasenides.minesweeper.proto.MATerrainCellProto&gt; terrain = 4;</code>
   */
  boolean containsTerrain(
      String key);
  /**
   * Use {@link #getTerrainMap()} instead.
   */
  @Deprecated
  java.util.Map<String, MATerrainCellProto>
  getTerrain();
  /**
   * <code>map&lt;string, .com.nkasenides.minesweeper.proto.MATerrainCellProto&gt; terrain = 4;</code>
   */
  java.util.Map<String, MATerrainCellProto>
  getTerrainMap();
  /**
   * <code>map&lt;string, .com.nkasenides.minesweeper.proto.MATerrainCellProto&gt; terrain = 4;</code>
   */

  MATerrainCellProto getTerrainOrDefault(
      String key,
      MATerrainCellProto defaultValue);
  /**
   * <code>map&lt;string, .com.nkasenides.minesweeper.proto.MATerrainCellProto&gt; terrain = 4;</code>
   */

  MATerrainCellProto getTerrainOrThrow(
      String key);

  /**
   * <code>uint64 timestamp = 5;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>int32 points = 6;</code>
   * @return The points.
   */
  int getPoints();
}
