// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto/MProto.proto

package com.nkasenides.minesweeper.proto;

/**
 * Protobuf type {@code com.nkasenides.minesweeper.proto.MAPartialStateProto}
 */
public final class MAPartialStateProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.nkasenides.minesweeper.proto.MAPartialStateProto)
    MAPartialStateProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MAPartialStateProto.newBuilder() to construct.
  private MAPartialStateProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MAPartialStateProto() {
    gameState_ = 0;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new MAPartialStateProto();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MAPartialStateProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            MAWorldSessionProto.Builder subBuilder = null;
            if (worldSession_ != null) {
              subBuilder = worldSession_.toBuilder();
            }
            worldSession_ = input.readMessage(MAWorldSessionProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(worldSession_);
              worldSession_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            gameState_ = rawValue;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              entities_ = com.google.protobuf.MapField.newMapField(
                  EntitiesDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<String, MAEntityProto>
            entities__ = input.readMessage(
                EntitiesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            entities_.getMutableMap().put(
                entities__.getKey(), entities__.getValue());
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              terrain_ = com.google.protobuf.MapField.newMapField(
                  TerrainDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000002;
            }
            com.google.protobuf.MapEntry<String, MATerrainCellProto>
            terrain__ = input.readMessage(
                TerrainDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            terrain_.getMutableMap().put(
                terrain__.getKey(), terrain__.getValue());
            break;
          }
          case 40: {

            timestamp_ = input.readUInt64();
            break;
          }
          case 48: {

            points_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return MProto.internal_static_com_nkasenides_minesweeper_proto_MAPartialStateProto_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 3:
        return internalGetEntities();
      case 4:
        return internalGetTerrain();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return MProto.internal_static_com_nkasenides_minesweeper_proto_MAPartialStateProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            MAPartialStateProto.class, Builder.class);
  }

  public static final int WORLDSESSION_FIELD_NUMBER = 1;
  private MAWorldSessionProto worldSession_;
  /**
   * <code>.com.nkasenides.minesweeper.proto.MAWorldSessionProto worldSession = 1;</code>
   * @return Whether the worldSession field is set.
   */
  @Override
  public boolean hasWorldSession() {
    return worldSession_ != null;
  }
  /**
   * <code>.com.nkasenides.minesweeper.proto.MAWorldSessionProto worldSession = 1;</code>
   * @return The worldSession.
   */
  @Override
  public MAWorldSessionProto getWorldSession() {
    return worldSession_ == null ? MAWorldSessionProto.getDefaultInstance() : worldSession_;
  }
  /**
   * <code>.com.nkasenides.minesweeper.proto.MAWorldSessionProto worldSession = 1;</code>
   */
  @Override
  public MAWorldSessionProtoOrBuilder getWorldSessionOrBuilder() {
    return getWorldSession();
  }

  public static final int GAMESTATE_FIELD_NUMBER = 2;
  private int gameState_;
  /**
   * <code>.com.nkasenides.minesweeper.proto.GameState gameState = 2;</code>
   * @return The enum numeric value on the wire for gameState.
   */
  @Override public int getGameStateValue() {
    return gameState_;
  }
  /**
   * <code>.com.nkasenides.minesweeper.proto.GameState gameState = 2;</code>
   * @return The gameState.
   */
  @Override public GameState getGameState() {
    @SuppressWarnings("deprecation")
    GameState result = GameState.valueOf(gameState_);
    return result == null ? GameState.UNRECOGNIZED : result;
  }

  public static final int ENTITIES_FIELD_NUMBER = 3;
  private static final class EntitiesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        String, MAEntityProto> defaultEntry =
            com.google.protobuf.MapEntry
            .<String, MAEntityProto>newDefaultInstance(
                MProto.internal_static_com_nkasenides_minesweeper_proto_MAPartialStateProto_EntitiesEntry_descriptor,
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                MAEntityProto.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      String, MAEntityProto> entities_;
  private com.google.protobuf.MapField<String, MAEntityProto>
  internalGetEntities() {
    if (entities_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          EntitiesDefaultEntryHolder.defaultEntry);
    }
    return entities_;
  }

  public int getEntitiesCount() {
    return internalGetEntities().getMap().size();
  }
  /**
   * <code>map&lt;string, .com.nkasenides.minesweeper.proto.MAEntityProto&gt; entities = 3;</code>
   */

  @Override
  public boolean containsEntities(
      String key) {
    if (key == null) { throw new NullPointerException(); }
    return internalGetEntities().getMap().containsKey(key);
  }
  /**
   * Use {@link #getEntitiesMap()} instead.
   */
  @Override
  @Deprecated
  public java.util.Map<String, MAEntityProto> getEntities() {
    return getEntitiesMap();
  }
  /**
   * <code>map&lt;string, .com.nkasenides.minesweeper.proto.MAEntityProto&gt; entities = 3;</code>
   */
  @Override

  public java.util.Map<String, MAEntityProto> getEntitiesMap() {
    return internalGetEntities().getMap();
  }
  /**
   * <code>map&lt;string, .com.nkasenides.minesweeper.proto.MAEntityProto&gt; entities = 3;</code>
   */
  @Override

  public MAEntityProto getEntitiesOrDefault(
      String key,
      MAEntityProto defaultValue) {
    if (key == null) { throw new NullPointerException(); }
    java.util.Map<String, MAEntityProto> map =
        internalGetEntities().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .com.nkasenides.minesweeper.proto.MAEntityProto&gt; entities = 3;</code>
   */
  @Override

  public MAEntityProto getEntitiesOrThrow(
      String key) {
    if (key == null) { throw new NullPointerException(); }
    java.util.Map<String, MAEntityProto> map =
        internalGetEntities().getMap();
    if (!map.containsKey(key)) {
      throw new IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int TERRAIN_FIELD_NUMBER = 4;
  private static final class TerrainDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        String, MATerrainCellProto> defaultEntry =
            com.google.protobuf.MapEntry
            .<String, MATerrainCellProto>newDefaultInstance(
                MProto.internal_static_com_nkasenides_minesweeper_proto_MAPartialStateProto_TerrainEntry_descriptor,
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                MATerrainCellProto.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      String, MATerrainCellProto> terrain_;
  private com.google.protobuf.MapField<String, MATerrainCellProto>
  internalGetTerrain() {
    if (terrain_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          TerrainDefaultEntryHolder.defaultEntry);
    }
    return terrain_;
  }

  public int getTerrainCount() {
    return internalGetTerrain().getMap().size();
  }
  /**
   * <code>map&lt;string, .com.nkasenides.minesweeper.proto.MATerrainCellProto&gt; terrain = 4;</code>
   */

  @Override
  public boolean containsTerrain(
      String key) {
    if (key == null) { throw new NullPointerException(); }
    return internalGetTerrain().getMap().containsKey(key);
  }
  /**
   * Use {@link #getTerrainMap()} instead.
   */
  @Override
  @Deprecated
  public java.util.Map<String, MATerrainCellProto> getTerrain() {
    return getTerrainMap();
  }
  /**
   * <code>map&lt;string, .com.nkasenides.minesweeper.proto.MATerrainCellProto&gt; terrain = 4;</code>
   */
  @Override

  public java.util.Map<String, MATerrainCellProto> getTerrainMap() {
    return internalGetTerrain().getMap();
  }
  /**
   * <code>map&lt;string, .com.nkasenides.minesweeper.proto.MATerrainCellProto&gt; terrain = 4;</code>
   */
  @Override

  public MATerrainCellProto getTerrainOrDefault(
      String key,
      MATerrainCellProto defaultValue) {
    if (key == null) { throw new NullPointerException(); }
    java.util.Map<String, MATerrainCellProto> map =
        internalGetTerrain().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .com.nkasenides.minesweeper.proto.MATerrainCellProto&gt; terrain = 4;</code>
   */
  @Override

  public MATerrainCellProto getTerrainOrThrow(
      String key) {
    if (key == null) { throw new NullPointerException(); }
    java.util.Map<String, MATerrainCellProto> map =
        internalGetTerrain().getMap();
    if (!map.containsKey(key)) {
      throw new IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 5;
  private long timestamp_;
  /**
   * <code>uint64 timestamp = 5;</code>
   * @return The timestamp.
   */
  @Override
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int POINTS_FIELD_NUMBER = 6;
  private int points_;
  /**
   * <code>int32 points = 6;</code>
   * @return The points.
   */
  @Override
  public int getPoints() {
    return points_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (worldSession_ != null) {
      output.writeMessage(1, getWorldSession());
    }
    if (gameState_ != GameState.ENDED_LOST_GameState.getNumber()) {
      output.writeEnum(2, gameState_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetEntities(),
        EntitiesDefaultEntryHolder.defaultEntry,
        3);
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetTerrain(),
        TerrainDefaultEntryHolder.defaultEntry,
        4);
    if (timestamp_ != 0L) {
      output.writeUInt64(5, timestamp_);
    }
    if (points_ != 0) {
      output.writeInt32(6, points_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (worldSession_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getWorldSession());
    }
    if (gameState_ != GameState.ENDED_LOST_GameState.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, gameState_);
    }
    for (java.util.Map.Entry<String, MAEntityProto> entry
         : internalGetEntities().getMap().entrySet()) {
      com.google.protobuf.MapEntry<String, MAEntityProto>
      entities__ = EntitiesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, entities__);
    }
    for (java.util.Map.Entry<String, MATerrainCellProto> entry
         : internalGetTerrain().getMap().entrySet()) {
      com.google.protobuf.MapEntry<String, MATerrainCellProto>
      terrain__ = TerrainDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, terrain__);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(5, timestamp_);
    }
    if (points_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, points_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof MAPartialStateProto)) {
      return super.equals(obj);
    }
    MAPartialStateProto other = (MAPartialStateProto) obj;

    if (hasWorldSession() != other.hasWorldSession()) return false;
    if (hasWorldSession()) {
      if (!getWorldSession()
          .equals(other.getWorldSession())) return false;
    }
    if (gameState_ != other.gameState_) return false;
    if (!internalGetEntities().equals(
        other.internalGetEntities())) return false;
    if (!internalGetTerrain().equals(
        other.internalGetTerrain())) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (getPoints()
        != other.getPoints()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasWorldSession()) {
      hash = (37 * hash) + WORLDSESSION_FIELD_NUMBER;
      hash = (53 * hash) + getWorldSession().hashCode();
    }
    hash = (37 * hash) + GAMESTATE_FIELD_NUMBER;
    hash = (53 * hash) + gameState_;
    if (!internalGetEntities().getMap().isEmpty()) {
      hash = (37 * hash) + ENTITIES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetEntities().hashCode();
    }
    if (!internalGetTerrain().getMap().isEmpty()) {
      hash = (37 * hash) + TERRAIN_FIELD_NUMBER;
      hash = (53 * hash) + internalGetTerrain().hashCode();
    }
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (37 * hash) + POINTS_FIELD_NUMBER;
    hash = (53 * hash) + getPoints();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static MAPartialStateProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MAPartialStateProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MAPartialStateProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MAPartialStateProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MAPartialStateProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MAPartialStateProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MAPartialStateProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MAPartialStateProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static MAPartialStateProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static MAPartialStateProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static MAPartialStateProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MAPartialStateProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(MAPartialStateProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.nkasenides.minesweeper.proto.MAPartialStateProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.nkasenides.minesweeper.proto.MAPartialStateProto)
      MAPartialStateProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MProto.internal_static_com_nkasenides_minesweeper_proto_MAPartialStateProto_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetEntities();
        case 4:
          return internalGetTerrain();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetMutableEntities();
        case 4:
          return internalGetMutableTerrain();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MProto.internal_static_com_nkasenides_minesweeper_proto_MAPartialStateProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MAPartialStateProto.class, Builder.class);
    }

    // Construct using com.nkasenides.minesweeper.proto.MAPartialStateProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (worldSessionBuilder_ == null) {
        worldSession_ = null;
      } else {
        worldSession_ = null;
        worldSessionBuilder_ = null;
      }
      gameState_ = 0;

      internalGetMutableEntities().clear();
      internalGetMutableTerrain().clear();
      timestamp_ = 0L;

      points_ = 0;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return MProto.internal_static_com_nkasenides_minesweeper_proto_MAPartialStateProto_descriptor;
    }

    @Override
    public MAPartialStateProto getDefaultInstanceForType() {
      return MAPartialStateProto.getDefaultInstance();
    }

    @Override
    public MAPartialStateProto build() {
      MAPartialStateProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public MAPartialStateProto buildPartial() {
      MAPartialStateProto result = new MAPartialStateProto(this);
      int from_bitField0_ = bitField0_;
      if (worldSessionBuilder_ == null) {
        result.worldSession_ = worldSession_;
      } else {
        result.worldSession_ = worldSessionBuilder_.build();
      }
      result.gameState_ = gameState_;
      result.entities_ = internalGetEntities();
      result.entities_.makeImmutable();
      result.terrain_ = internalGetTerrain();
      result.terrain_.makeImmutable();
      result.timestamp_ = timestamp_;
      result.points_ = points_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof MAPartialStateProto) {
        return mergeFrom((MAPartialStateProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(MAPartialStateProto other) {
      if (other == MAPartialStateProto.getDefaultInstance()) return this;
      if (other.hasWorldSession()) {
        mergeWorldSession(other.getWorldSession());
      }
      if (other.gameState_ != 0) {
        setGameStateValue(other.getGameStateValue());
      }
      internalGetMutableEntities().mergeFrom(
          other.internalGetEntities());
      internalGetMutableTerrain().mergeFrom(
          other.internalGetTerrain());
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (other.getPoints() != 0) {
        setPoints(other.getPoints());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      MAPartialStateProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (MAPartialStateProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private MAWorldSessionProto worldSession_;
    private com.google.protobuf.SingleFieldBuilderV3<
        MAWorldSessionProto, MAWorldSessionProto.Builder, MAWorldSessionProtoOrBuilder> worldSessionBuilder_;
    /**
     * <code>.com.nkasenides.minesweeper.proto.MAWorldSessionProto worldSession = 1;</code>
     * @return Whether the worldSession field is set.
     */
    public boolean hasWorldSession() {
      return worldSessionBuilder_ != null || worldSession_ != null;
    }
    /**
     * <code>.com.nkasenides.minesweeper.proto.MAWorldSessionProto worldSession = 1;</code>
     * @return The worldSession.
     */
    public MAWorldSessionProto getWorldSession() {
      if (worldSessionBuilder_ == null) {
        return worldSession_ == null ? MAWorldSessionProto.getDefaultInstance() : worldSession_;
      } else {
        return worldSessionBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.nkasenides.minesweeper.proto.MAWorldSessionProto worldSession = 1;</code>
     */
    public Builder setWorldSession(MAWorldSessionProto value) {
      if (worldSessionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        worldSession_ = value;
        onChanged();
      } else {
        worldSessionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.nkasenides.minesweeper.proto.MAWorldSessionProto worldSession = 1;</code>
     */
    public Builder setWorldSession(
        MAWorldSessionProto.Builder builderForValue) {
      if (worldSessionBuilder_ == null) {
        worldSession_ = builderForValue.build();
        onChanged();
      } else {
        worldSessionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.nkasenides.minesweeper.proto.MAWorldSessionProto worldSession = 1;</code>
     */
    public Builder mergeWorldSession(MAWorldSessionProto value) {
      if (worldSessionBuilder_ == null) {
        if (worldSession_ != null) {
          worldSession_ =
            MAWorldSessionProto.newBuilder(worldSession_).mergeFrom(value).buildPartial();
        } else {
          worldSession_ = value;
        }
        onChanged();
      } else {
        worldSessionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.nkasenides.minesweeper.proto.MAWorldSessionProto worldSession = 1;</code>
     */
    public Builder clearWorldSession() {
      if (worldSessionBuilder_ == null) {
        worldSession_ = null;
        onChanged();
      } else {
        worldSession_ = null;
        worldSessionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.nkasenides.minesweeper.proto.MAWorldSessionProto worldSession = 1;</code>
     */
    public MAWorldSessionProto.Builder getWorldSessionBuilder() {
      
      onChanged();
      return getWorldSessionFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.nkasenides.minesweeper.proto.MAWorldSessionProto worldSession = 1;</code>
     */
    public MAWorldSessionProtoOrBuilder getWorldSessionOrBuilder() {
      if (worldSessionBuilder_ != null) {
        return worldSessionBuilder_.getMessageOrBuilder();
      } else {
        return worldSession_ == null ?
            MAWorldSessionProto.getDefaultInstance() : worldSession_;
      }
    }
    /**
     * <code>.com.nkasenides.minesweeper.proto.MAWorldSessionProto worldSession = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        MAWorldSessionProto, MAWorldSessionProto.Builder, MAWorldSessionProtoOrBuilder>
        getWorldSessionFieldBuilder() {
      if (worldSessionBuilder_ == null) {
        worldSessionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            MAWorldSessionProto, MAWorldSessionProto.Builder, MAWorldSessionProtoOrBuilder>(
                getWorldSession(),
                getParentForChildren(),
                isClean());
        worldSession_ = null;
      }
      return worldSessionBuilder_;
    }

    private int gameState_ = 0;
    /**
     * <code>.com.nkasenides.minesweeper.proto.GameState gameState = 2;</code>
     * @return The enum numeric value on the wire for gameState.
     */
    @Override public int getGameStateValue() {
      return gameState_;
    }
    /**
     * <code>.com.nkasenides.minesweeper.proto.GameState gameState = 2;</code>
     * @param value The enum numeric value on the wire for gameState to set.
     * @return This builder for chaining.
     */
    public Builder setGameStateValue(int value) {
      
      gameState_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.nkasenides.minesweeper.proto.GameState gameState = 2;</code>
     * @return The gameState.
     */
    @Override
    public GameState getGameState() {
      @SuppressWarnings("deprecation")
      GameState result = GameState.valueOf(gameState_);
      return result == null ? GameState.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.nkasenides.minesweeper.proto.GameState gameState = 2;</code>
     * @param value The gameState to set.
     * @return This builder for chaining.
     */
    public Builder setGameState(GameState value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      gameState_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.nkasenides.minesweeper.proto.GameState gameState = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearGameState() {
      
      gameState_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        String, MAEntityProto> entities_;
    private com.google.protobuf.MapField<String, MAEntityProto>
    internalGetEntities() {
      if (entities_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            EntitiesDefaultEntryHolder.defaultEntry);
      }
      return entities_;
    }
    private com.google.protobuf.MapField<String, MAEntityProto>
    internalGetMutableEntities() {
      onChanged();;
      if (entities_ == null) {
        entities_ = com.google.protobuf.MapField.newMapField(
            EntitiesDefaultEntryHolder.defaultEntry);
      }
      if (!entities_.isMutable()) {
        entities_ = entities_.copy();
      }
      return entities_;
    }

    public int getEntitiesCount() {
      return internalGetEntities().getMap().size();
    }
    /**
     * <code>map&lt;string, .com.nkasenides.minesweeper.proto.MAEntityProto&gt; entities = 3;</code>
     */

    @Override
    public boolean containsEntities(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetEntities().getMap().containsKey(key);
    }
    /**
     * Use {@link #getEntitiesMap()} instead.
     */
    @Override
    @Deprecated
    public java.util.Map<String, MAEntityProto> getEntities() {
      return getEntitiesMap();
    }
    /**
     * <code>map&lt;string, .com.nkasenides.minesweeper.proto.MAEntityProto&gt; entities = 3;</code>
     */
    @Override

    public java.util.Map<String, MAEntityProto> getEntitiesMap() {
      return internalGetEntities().getMap();
    }
    /**
     * <code>map&lt;string, .com.nkasenides.minesweeper.proto.MAEntityProto&gt; entities = 3;</code>
     */
    @Override

    public MAEntityProto getEntitiesOrDefault(
        String key,
        MAEntityProto defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, MAEntityProto> map =
          internalGetEntities().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .com.nkasenides.minesweeper.proto.MAEntityProto&gt; entities = 3;</code>
     */
    @Override

    public MAEntityProto getEntitiesOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, MAEntityProto> map =
          internalGetEntities().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearEntities() {
      internalGetMutableEntities().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .com.nkasenides.minesweeper.proto.MAEntityProto&gt; entities = 3;</code>
     */

    public Builder removeEntities(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      internalGetMutableEntities().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @Deprecated
    public java.util.Map<String, MAEntityProto>
    getMutableEntities() {
      return internalGetMutableEntities().getMutableMap();
    }
    /**
     * <code>map&lt;string, .com.nkasenides.minesweeper.proto.MAEntityProto&gt; entities = 3;</code>
     */
    public Builder putEntities(
        String key,
        MAEntityProto value) {
      if (key == null) { throw new NullPointerException(); }
      if (value == null) { throw new NullPointerException(); }
      internalGetMutableEntities().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, .com.nkasenides.minesweeper.proto.MAEntityProto&gt; entities = 3;</code>
     */

    public Builder putAllEntities(
        java.util.Map<String, MAEntityProto> values) {
      internalGetMutableEntities().getMutableMap()
          .putAll(values);
      return this;
    }

    private com.google.protobuf.MapField<
        String, MATerrainCellProto> terrain_;
    private com.google.protobuf.MapField<String, MATerrainCellProto>
    internalGetTerrain() {
      if (terrain_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            TerrainDefaultEntryHolder.defaultEntry);
      }
      return terrain_;
    }
    private com.google.protobuf.MapField<String, MATerrainCellProto>
    internalGetMutableTerrain() {
      onChanged();;
      if (terrain_ == null) {
        terrain_ = com.google.protobuf.MapField.newMapField(
            TerrainDefaultEntryHolder.defaultEntry);
      }
      if (!terrain_.isMutable()) {
        terrain_ = terrain_.copy();
      }
      return terrain_;
    }

    public int getTerrainCount() {
      return internalGetTerrain().getMap().size();
    }
    /**
     * <code>map&lt;string, .com.nkasenides.minesweeper.proto.MATerrainCellProto&gt; terrain = 4;</code>
     */

    @Override
    public boolean containsTerrain(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetTerrain().getMap().containsKey(key);
    }
    /**
     * Use {@link #getTerrainMap()} instead.
     */
    @Override
    @Deprecated
    public java.util.Map<String, MATerrainCellProto> getTerrain() {
      return getTerrainMap();
    }
    /**
     * <code>map&lt;string, .com.nkasenides.minesweeper.proto.MATerrainCellProto&gt; terrain = 4;</code>
     */
    @Override

    public java.util.Map<String, MATerrainCellProto> getTerrainMap() {
      return internalGetTerrain().getMap();
    }
    /**
     * <code>map&lt;string, .com.nkasenides.minesweeper.proto.MATerrainCellProto&gt; terrain = 4;</code>
     */
    @Override

    public MATerrainCellProto getTerrainOrDefault(
        String key,
        MATerrainCellProto defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, MATerrainCellProto> map =
          internalGetTerrain().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .com.nkasenides.minesweeper.proto.MATerrainCellProto&gt; terrain = 4;</code>
     */
    @Override

    public MATerrainCellProto getTerrainOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, MATerrainCellProto> map =
          internalGetTerrain().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearTerrain() {
      internalGetMutableTerrain().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .com.nkasenides.minesweeper.proto.MATerrainCellProto&gt; terrain = 4;</code>
     */

    public Builder removeTerrain(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      internalGetMutableTerrain().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @Deprecated
    public java.util.Map<String, MATerrainCellProto>
    getMutableTerrain() {
      return internalGetMutableTerrain().getMutableMap();
    }
    /**
     * <code>map&lt;string, .com.nkasenides.minesweeper.proto.MATerrainCellProto&gt; terrain = 4;</code>
     */
    public Builder putTerrain(
        String key,
        MATerrainCellProto value) {
      if (key == null) { throw new NullPointerException(); }
      if (value == null) { throw new NullPointerException(); }
      internalGetMutableTerrain().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, .com.nkasenides.minesweeper.proto.MATerrainCellProto&gt; terrain = 4;</code>
     */

    public Builder putAllTerrain(
        java.util.Map<String, MATerrainCellProto> values) {
      internalGetMutableTerrain().getMutableMap()
          .putAll(values);
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>uint64 timestamp = 5;</code>
     * @return The timestamp.
     */
    @Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>uint64 timestamp = 5;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 timestamp = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private int points_ ;
    /**
     * <code>int32 points = 6;</code>
     * @return The points.
     */
    @Override
    public int getPoints() {
      return points_;
    }
    /**
     * <code>int32 points = 6;</code>
     * @param value The points to set.
     * @return This builder for chaining.
     */
    public Builder setPoints(int value) {
      
      points_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 points = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPoints() {
      
      points_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.nkasenides.minesweeper.proto.MAPartialStateProto)
  }

  // @@protoc_insertion_point(class_scope:com.nkasenides.minesweeper.proto.MAPartialStateProto)
  private static final MAPartialStateProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new MAPartialStateProto();
  }

  public static MAPartialStateProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MAPartialStateProto>
      PARSER = new com.google.protobuf.AbstractParser<MAPartialStateProto>() {
    @Override
    public MAPartialStateProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MAPartialStateProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MAPartialStateProto> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<MAPartialStateProto> getParserForType() {
    return PARSER;
  }

  @Override
  public MAPartialStateProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

