// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto/MProto.proto

package com.nkasenides.minesweeper.proto;

public interface MAPlayerProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.nkasenides.minesweeper.proto.MAPlayerProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string password = 1;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 1;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string teamID = 2;</code>
   * @return The teamID.
   */
  java.lang.String getTeamID();
  /**
   * <code>string teamID = 2;</code>
   * @return The bytes for teamID.
   */
  com.google.protobuf.ByteString
      getTeamIDBytes();

  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string id = 4;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 4;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>uint64 createdOn = 5;</code>
   * @return The createdOn.
   */
  long getCreatedOn();
}
