// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto/MProto.proto

package com.nkasenides.minesweeper.proto;

public interface MATerrainCellProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.nkasenides.minesweeper.proto.MATerrainCellProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.nkasenides.minesweeper.proto.RevealState revealState = 1;</code>
   * @return The enum numeric value on the wire for revealState.
   */
  int getRevealStateValue();
  /**
   * <code>.com.nkasenides.minesweeper.proto.RevealState revealState = 1;</code>
   * @return The revealState.
   */
  com.nkasenides.minesweeper.proto.RevealState getRevealState();

  /**
   * <code>.com.nkasenides.minesweeper.proto.MatrixPositionProto position = 2;</code>
   * @return Whether the position field is set.
   */
  boolean hasPosition();
  /**
   * <code>.com.nkasenides.minesweeper.proto.MatrixPositionProto position = 2;</code>
   * @return The position.
   */
  com.nkasenides.minesweeper.proto.MatrixPositionProto getPosition();
  /**
   * <code>.com.nkasenides.minesweeper.proto.MatrixPositionProto position = 2;</code>
   */
  com.nkasenides.minesweeper.proto.MatrixPositionProtoOrBuilder getPositionOrBuilder();

  /**
   * <code>bool isMined = 3;</code>
   * @return The isMined.
   */
  boolean getIsMined();
}
