// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto/MProto.proto

package com.nkasenides.minesweeper.proto;

public interface MATerrainIdentifierProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.nkasenides.minesweeper.proto.MATerrainIdentifierProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string chunkID = 2;</code>
   * @return The chunkID.
   */
  java.lang.String getChunkID();
  /**
   * <code>string chunkID = 2;</code>
   * @return The bytes for chunkID.
   */
  com.google.protobuf.ByteString
      getChunkIDBytes();

  /**
   * <code>string worldID = 3;</code>
   * @return The worldID.
   */
  java.lang.String getWorldID();
  /**
   * <code>string worldID = 3;</code>
   * @return The bytes for worldID.
   */
  com.google.protobuf.ByteString
      getWorldIDBytes();

  /**
   * <code>.com.nkasenides.minesweeper.proto.MatrixPositionProto chunkPosition = 4;</code>
   * @return Whether the chunkPosition field is set.
   */
  boolean hasChunkPosition();
  /**
   * <code>.com.nkasenides.minesweeper.proto.MatrixPositionProto chunkPosition = 4;</code>
   * @return The chunkPosition.
   */
  com.nkasenides.minesweeper.proto.MatrixPositionProto getChunkPosition();
  /**
   * <code>.com.nkasenides.minesweeper.proto.MatrixPositionProto chunkPosition = 4;</code>
   */
  com.nkasenides.minesweeper.proto.MatrixPositionProtoOrBuilder getChunkPositionOrBuilder();
}
