// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto/MProto.proto

package com.nkasenides.minesweeper.proto;

public interface StartGameRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.nkasenides.minesweeper.proto.StartGameRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string gameID = 1;</code>
   * @return The gameID.
   */
  java.lang.String getGameID();
  /**
   * <code>string gameID = 1;</code>
   * @return The bytes for gameID.
   */
  com.google.protobuf.ByteString
      getGameIDBytes();
}
