// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto/MProto.proto

package com.nkasenides.minesweeper.proto;

public interface UpdateStateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.nkasenides.minesweeper.proto.UpdateStateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.com.nkasenides.minesweeper.proto.MAStateUpdateProto stateUpdate = 2;</code>
   * @return Whether the stateUpdate field is set.
   */
  boolean hasStateUpdate();
  /**
   * <code>.com.nkasenides.minesweeper.proto.MAStateUpdateProto stateUpdate = 2;</code>
   * @return The stateUpdate.
   */
  MAStateUpdateProto getStateUpdate();
  /**
   * <code>.com.nkasenides.minesweeper.proto.MAStateUpdateProto stateUpdate = 2;</code>
   */
  MAStateUpdateProtoOrBuilder getStateUpdateOrBuilder();

  /**
   * <code>.com.nkasenides.minesweeper.proto.UpdateStateResponse.Status status = 3;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.com.nkasenides.minesweeper.proto.UpdateStateResponse.Status status = 3;</code>
   * @return The status.
   */
  UpdateStateResponse.Status getStatus();
}
