/* --------------------------------------------------------------------------------
  This file was automatically generated by the Athlos Project Editor.
  Athlos Framework: http://nkasenides.github.io/athlos
  Generated on: 16-11-2021 12:37:22
  Athlos Project Editor, v0.1.0 BETA
-------------------------------------------------------------------------------- */

package com.nkasenides.minesweeper.client;
import com.nkasenides.minesweeper.model.*;
import com.nkasenides.minesweeper.proto.*;
import com.nkasenides.athlos.client.DedicatedGameClient;


public class MAClient extends DedicatedGameClient<MAPartialStateProto, MAGameSession, MAWorldSession, MAPlayer, MAWorld, MAEntityProto, MATerrainCellProto> {

    public final MAStubManager stubs = new MAStubManager(mainChannel);

    public MAClient(String ipAddress, int PORT) {
        super(ipAddress, PORT);
    }

    public static void main(String[] args) {
        MAClient client = new MAClient("localhost", 25000);
        client.start();
        MAStubManager a = new MAStubManager(client.mainChannel);
        a.createGame.sendAndWait(CreateGameRequest.newBuilder()
                        .setWidth(10)
                        .setHeight(10)
                        .setDifficulty(Difficulty.EASY_Difficulty)
                        .setMaxPlayers(10)
                .build()
        );
    }


}
